#!/usr/bin/env python3
"""Generate ``src/screencap/_provisioned.py`` from the build environment.

The non-secret cloud-auth client credentials (the public OAuth client id and the
restricted Firebase Web API key) must reach release binaries WITHOUT being
committed to source — placeholders stay in ``src/screencap/auth.py``; the real
values are injected at build time into a gitignored ``_provisioned`` module that
``auth.py`` consults (precedence: explicit env var > ``_provisioned`` > placeholder).

This script is the SINGLE writer of ``_provisioned.py``; never hand-edit that file.
It reads ``SCREENCAP_OAUTH_CLIENT_ID`` and ``SCREENCAP_FIREBASE_API_KEY`` from the
environment and exits non-zero WITHOUT writing anything if either is missing — so a
release build that forgot to source the secrets fails here rather than silently
shipping a placeholder (broken-sign-in) binary (the U2 build guard is the net that
catches the same failure on the built binary).

Usage (run after ``pip install -e`` and BEFORE ``pyinstaller``):

    SCREENCAP_OAUTH_CLIENT_ID=... SCREENCAP_FIREBASE_API_KEY=... \
        python scripts/generate_provisioned.py

The values are non-secret by design (a public RFC 8252 native OAuth client id and a
Firebase Web API key restricted to Identity Toolkit + Token Service) — see
``docs/runbooks/cloud-auth-setup.md``. "Inject, don't commit" is a keep-it-out-of-git
preference, not a security boundary: the values still ship in the release tarball.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# The two env vars the build must supply. Names mirror the client-side env
# overrides in ``auth.py`` so an operator sets one consistent pair.
_OAUTH_CLIENT_ID_ENV = "SCREENCAP_OAUTH_CLIENT_ID"
_FIREBASE_API_KEY_ENV = "SCREENCAP_FIREBASE_API_KEY"

# Written relative to this script so the output lands correctly regardless of cwd.
_OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent / "src" / "screencap" / "_provisioned.py"
)

_TEMPLATE = '''\
# AUTO-GENERATED by scripts/generate_provisioned.py — DO NOT EDIT, DO NOT COMMIT.
#
# Build-time-injected, non-secret cloud-auth client credentials consulted by
# screencap.auth (precedence: explicit env var > this module > placeholder).
# Gitignored; absent from source checkouts and the test suite. Regenerate via:
#     python scripts/generate_provisioned.py
"""Injected cloud-auth client credentials (generated; non-secret; not committed)."""

FIREBASE_API_KEY = {api_key!r}
OAUTH_CLIENT_ID = {client_id!r}
'''


def main() -> int:
    client_id = os.environ.get(_OAUTH_CLIENT_ID_ENV, "").strip()
    api_key = os.environ.get(_FIREBASE_API_KEY_ENV, "").strip()

    # Remove any stale module FIRST so a fail-closed exit never leaves a prior
    # build's _provisioned.py in the (gitignored, build-persistent) source tree to
    # be silently re-bundled with outdated/rotated creds.
    _OUTPUT_PATH.unlink(missing_ok=True)

    missing = [
        name
        for name, value in (
            (_OAUTH_CLIENT_ID_ENV, client_id),
            (_FIREBASE_API_KEY_ENV, api_key),
        )
        if not value
    ]
    if missing:
        # Fail closed, writing nothing: a release build that did not receive the
        # injected credentials must not produce a placeholder binary (R6).
        names = ", ".join(missing)
        # GitHub Actions annotation on STDOUT so the Actions UI surfaces the cause
        # inline instead of a bare "Process completed with exit code 1".
        print(
            f"::error::generate_provisioned.py: missing required environment "
            f"variable(s): {names}. Set them before a release build "
            "(see docs/runbooks/cloud-auth-setup.md)."
        )
        # Human-readable detail on stderr for local/non-Actions runs.
        print(
            "ERROR: refusing to generate _provisioned.py — missing required "
            f"environment variable(s): {names}.\n"
            "Set both before building a release (see docs/runbooks/cloud-auth-setup.md).",
            file=sys.stderr,
        )
        return 1

    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(
        _TEMPLATE.format(api_key=api_key, client_id=client_id), encoding="utf-8"
    )
    # Print the path only — never echo the credential values.
    print(f"Wrote {_OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
