import CryptoKit
import XCTest
@testable import ScreenCap

/// Search U6: the Swift read-side decrypt must be byte-compatible with Python
/// `screencap.corpus_crypto`. The fixtures below were produced by the Python
/// encryptor (deterministic key 00..1f); if either side's format drifts, the
/// interop assertion fails — which is the whole point of pinning them here.
final class CorpusCryptoTests: XCTestCase {

    // Generated by src/screencap/corpus_crypto.encrypt (see the plan's U6 test).
    private let keyB64 = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8="
    private let tokenB64 = "U0NFMfx3zh6oD7AlszjYFYyfPHHS12KJ5oI8pk54vftkNwvZrm6q+4PS6773ci7m+Z/vCyV9CCQ="
    private let plaintextB64 = "/9j/4GhlbGxvLWNvcnB1cy1zdGlsbP/Z"
    private let recording = "2026-07-11-demo"
    private let stillName = "1720000000.500000.jpg"

    private func crypto() -> CorpusCrypto {
        CorpusCrypto(key: SymmetricKey(data: Data(base64Encoded: keyB64)!))
    }

    func testDecryptsPythonProducedToken() throws {
        let token = Data(base64Encoded: tokenB64)!
        let expected = Data(base64Encoded: plaintextB64)!
        let decrypted = try crypto().decrypt(token, recording: recording, name: stillName)
        XCTAssertEqual(decrypted, expected)
    }

    func testAadMatchesPythonCanonicalForm() {
        // Python: json.dumps({"n":name,"r":recording}, separators=(",",":"), sort_keys=True)
        let expected = "{\"n\":\"\(stillName)\",\"r\":\"\(recording)\"}"
        XCTAssertEqual(CorpusCrypto.aad(recording: recording, name: stillName), Data(expected.utf8))
    }

    func testWrongAadFailsDecrypt() {
        let token = Data(base64Encoded: tokenB64)!
        XCTAssertThrowsError(try crypto().decrypt(token, recording: "other-recording", name: stillName))
        XCTAssertThrowsError(try crypto().decrypt(token, recording: recording, name: "9.jpg"))
    }

    func testTamperedTokenFails() {
        var token = Data(base64Encoded: tokenB64)!
        token[token.count - 1] ^= 0x01  // flip a tag bit
        XCTAssertThrowsError(try crypto().decrypt(token, recording: recording, name: stillName))
    }

    func testBadMagicRejected() {
        XCTAssertThrowsError(
            try crypto().decrypt(Data("XXXXnope".utf8), recording: recording, name: stillName)
        ) { error in
            XCTAssertEqual(error as? CorpusCryptoError, .badFormat)
        }
    }

    func testLogicalStillNameStripsEnc() {
        let enc = URL(fileURLWithPath: "/r/screenshots/1.500000.jpg.enc")
        let plain = URL(fileURLWithPath: "/r/screenshots/1.500000.jpg")
        XCTAssertEqual(CorpusCrypto.logicalStillName(enc), "1.500000.jpg")
        XCTAssertEqual(CorpusCrypto.logicalStillName(plain), "1.500000.jpg")
        XCTAssertTrue(CorpusCrypto.isEncryptedStill(enc))
        XCTAssertFalse(CorpusCrypto.isEncryptedStill(plain))
    }
}

extension CorpusCryptoError: Equatable {
    public static func == (lhs: CorpusCryptoError, rhs: CorpusCryptoError) -> Bool {
        switch (lhs, rhs) {
        case (.keyUnavailable, .keyUnavailable), (.badFormat, .badFormat), (.decryptFailed, .decryptFailed):
            return true
        default:
            return false
        }
    }
}
